uint8 slave_id # 从机ID
uint8 mode     # 1~6, 对应以下6种控制模式
# 1. 位置
# 2. 速度
# 3. 电流，目前仅支持二代手
# 4. PWM，目前仅支持二代手
# 5. 位置+期望时间，目前仅支持二代手
# 6. 位置+期望速度，目前仅支持二代手

uint8 motor_id              # 手指ID
uint16 position             # 位置     
int16 speed                 # 速度
int16 current               # 电流
int16 pwm                   # PWM
uint16 duration             # 期望时间, 单位ms
---
bool success        # 执行结果
