# 请求部分
uint8 slave_id            # 从机ID
# bool get_sku_type         # 是否获取设备 SKU 类型
# bool get_serial_number    # 是否获取设备序列号
# bool get_firmware_version # 是否获取固件版本
bool get_voltage          # 是否获取电池电压
bool get_turbo_mode       # 是否获取配置信息（turbo模式）
# bool get_force_level      # 是否获取力度级别
---
# 响应部分
bool success              # 操作是否成功
uint8 sku_type            # 设备 SKU 类型
string serial_number      # 设备序列号
string firmware_version   # 固件版本
uint16 voltage            # 电池电压
bool turbo_mode           # 是否处于 turbo 模式
# uint8 force_level         # 当前力度级别